version: "3.7"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: api-swagger-ui
    volumes:
      - ./openapi.yml:/usr/share/nginx/html/openapi.yml
      - ./resources:/usr/share/nginx/html/resources
    environment:
      API_URL: openapi.yml
    ports:
      - "8080:8080"
  swagger-api:
    image: stoplight/prism:3
    container_name: warifu-swagger-api
    ports:
      - "8081:4010"
    command: mock -h 0.0.0.0 /openapi.yml
    volumes:
      - ./merged/openapi/openapi.yaml:/openapi.yml
